pages = [{"l":"index.html#","e":false,"i":"","n":"better-files","t":"better-files","d":"","k":"static"},
{"l":"better/files.html#","e":false,"i":"","n":"better.files","t":"better.files","d":"","k":"package"},
{"l":"better/files.html#DefaultBufferSize-0","e":false,"i":"","n":"DefaultBufferSize","t":"DefaultBufferSize: Int","d":"better.files","k":"val"},
{"l":"better/files.html#DefaultCharset-0","e":false,"i":"","n":"DefaultCharset","t":"DefaultCharset: Charset","d":"better.files","k":"val"},
{"l":"better/files.html#EOF-0","e":false,"i":"","n":"EOF","t":"EOF: Int","d":"better.files","k":"val"},
{"l":"better/files.html#using-b7c","e":false,"i":"","n":"using","t":"using[A : Disposable, B](resource: A)(f: A => B): B","d":"better.files","k":"def"},
{"l":"better/files/BomEncoder.html#","e":false,"i":"","n":"BomEncoder","t":"BomEncoder(charset: Charset) extends CharsetEncoder","d":"better.files","k":"class"},
{"l":"better/files/Disposable.html#","e":false,"i":"","n":"Disposable","t":"Disposable[-A]","d":"better.files","k":"trait"},
{"l":"better/files/Disposable.html#dispose-fffff71f","e":false,"i":"","n":"dispose","t":"dispose(resource: A): Unit","d":"better.files.Disposable","k":"def"},
{"l":"better/files/Disposable.html#disposeSilently-fffff71f","e":false,"i":"","n":"disposeSilently","t":"disposeSilently(resource: A): Unit","d":"better.files.Disposable","k":"def"},
{"l":"better/files/Disposable$.html#","e":false,"i":"","n":"Disposable","t":"Disposable","d":"better.files","k":"object"},
{"l":"better/files/Disposable$.html#apply-d55","e":false,"i":"","n":"apply","t":"apply[A](disposeFunction: A => Any): Disposable[A]","d":"better.files.Disposable","k":"def"},
{"l":"better/files/Disposable$.html#apply-e76","e":false,"i":"","n":"apply","t":"apply[A](disposeMethod: => Unit): Disposable[A]","d":"better.files.Disposable","k":"def"},
{"l":"better/files/Disposable$.html#closableDisposer-0","e":false,"i":"","n":"closableDisposer","t":"closableDisposer: Disposable[AutoCloseable]","d":"better.files.Disposable","k":"val"},
{"l":"better/files/Disposable$.html#fileDisposer-0","e":false,"i":"","n":"fileDisposer","t":"fileDisposer: Disposable[File]","d":"better.files.Disposable","k":"val"},
{"l":"better/files/Disposable$.html#traversableDisposer-fffffad1","e":false,"i":"","n":"traversableDisposer","t":"traversableDisposer[A](implicit disposer: Disposable[A]): Disposable[Iterable[A]]","d":"better.files.Disposable","k":"def"},
{"l":"better/files/Dispose.html#","e":false,"i":"","n":"Dispose","t":"Dispose[A](val resource: A)(implicit disposer: Disposable[A])","d":"better.files","k":"class"},
{"l":"better/files/Dispose.html#apply-5d3","e":false,"i":"","n":"apply","t":"apply[B](f: A => B): B","d":"better.files.Dispose","k":"def"},
{"l":"better/files/Dispose.html#flatMap-43","e":false,"i":"","n":"flatMap","t":"flatMap[B, F[_]](f: A => F[B])(implicit fv: FlatMap[F]): Output[B]","d":"better.files.Dispose","k":"def"},
{"l":"better/files/Dispose.html#foreach-58c","e":false,"i":"","n":"foreach","t":"foreach[U](f: A => U): Unit","d":"better.files.Dispose","k":"def"},
{"l":"better/files/Dispose.html#get-993","e":false,"i":"","n":"get","t":"get(): A","d":"better.files.Dispose","k":"def"},
{"l":"better/files/Dispose.html#iterator-fffffcf6","e":false,"i":"","n":"iterator","t":"iterator[B](f: A => Iterator[B]): Iterator[B]","d":"better.files.Dispose","k":"def"},
{"l":"better/files/Dispose.html#map-24a","e":false,"i":"","n":"map","t":"map[B](f: A => B): Dispose[B]","d":"better.files.Dispose","k":"def"},
{"l":"better/files/Dispose.html#withFilter-fffff81b","e":false,"i":"","n":"withFilter","t":"withFilter(f: A => Boolean): Dispose.this.type","d":"better.files.Dispose","k":"def"},
{"l":"better/files/Dispose$.html#","e":false,"i":"","n":"Dispose","t":"Dispose","d":"better.files","k":"object"},
{"l":"better/files/Dispose$$FlatMap$.html#","e":false,"i":"","n":"FlatMap","t":"FlatMap","d":"better.files.Dispose","k":"object"},
{"l":"better/files/Dispose$$FlatMap$$Implicits.html#","e":false,"i":"","n":"Implicits","t":"Implicits","d":"better.files.Dispose.FlatMap","k":"trait"},
{"l":"better/files/Dispose$$FlatMap$$Implicits$disposeFlatMap$.html#","e":false,"i":"","n":"disposeFlatMap","t":"disposeFlatMap extends FlatMap[Dispose]","d":"better.files.Dispose.FlatMap.Implicits","k":"object"},
{"l":"better/files/Dispose$$FlatMap$$Implicits$disposeFlatMap$.html#Output-0","e":false,"i":"","n":"Output","t":"Output[X] = Dispose[X]","d":"better.files.Dispose.FlatMap.Implicits.disposeFlatMap","k":"type"},
{"l":"better/files/Dispose$$FlatMap$$Implicits$traversableFlatMap$.html#","e":false,"i":"","n":"traversableFlatMap","t":"traversableFlatMap extends FlatMap[GenTraversableOnce]","d":"better.files.Dispose.FlatMap.Implicits","k":"object"},
{"l":"better/files/Dispose$$FlatMap$$Implicits$traversableFlatMap$.html#Output-0","e":false,"i":"","n":"Output","t":"Output[X] = Iterator[X]","d":"better.files.Dispose.FlatMap.Implicits.traversableFlatMap","k":"type"},
{"l":"better/files/Dispose$$FlatMap.html#","e":false,"i":"","n":"FlatMap","t":"FlatMap[-F[_]]","d":"better.files.Dispose","k":"trait"},
{"l":"better/files/Dispose$$FlatMap.html#Output-0","e":false,"i":"","n":"Output","t":"Output[_]","d":"better.files.Dispose.FlatMap","k":"type"},
{"l":"better/files/Dispose$$FlatMap.html#apply-fffffb68","e":false,"i":"","n":"apply","t":"apply[A, B](a: Dispose[A])(f: A => F[B]): Output[B]","d":"better.files.Dispose.FlatMap","k":"def"},
{"l":"better/files/Dsl$.html#","e":false,"i":"","n":"Dsl","t":"Dsl","d":"better.files","k":"object"},
{"l":"better/files/Dsl$.html#..-0","e":false,"i":"","n":"..","t":"..: File => File","d":"better.files.Dsl","k":"val"},
{"l":"better/files/Dsl$.html#SymbolicOperations-c81","e":false,"i":"","n":"SymbolicOperations","t":"SymbolicOperations(file: File): SymbolicOperations","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#.-0","e":false,"i":"","n":"`.`","t":"`.`: File => File","d":"better.files.Dsl","k":"val"},
{"l":"better/files/Dsl$.html#cat-716","e":false,"i":"","n":"cat","t":"cat(files: File*): Seq[Iterator[Byte]]","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#chgrp-d45","e":false,"i":"","n":"chgrp","t":"chgrp(group: String, file: File): File","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#chmod-d45","e":false,"i":"","n":"chmod","t":"chmod(permissions: String, file: File): File","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#chmod_+-df0","e":false,"i":"","n":"chmod_+","t":"chmod_+(permission: PosixFilePermission, file: File): File","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#chmod_--df0","e":false,"i":"","n":"chmod_-","t":"chmod_-(permission: PosixFilePermission, file: File): File","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#chown-d45","e":false,"i":"","n":"chown","t":"chown(owner: String, file: File): File","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#cp-fffff951","e":false,"i":"","n":"cp","t":"cp(from: File, to: File): File","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#cwd-0","e":false,"i":"","n":"cwd","t":"cwd: File","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#del-20","e":false,"i":"","n":"del","t":"del(file: File): File","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#dir-fffffce5","e":false,"i":"","n":"dir","t":"dir(file: File): Iterator[File]","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#gzip-fffff951","e":false,"i":"","n":"gzip","t":"gzip(file: File)(destination: File): File","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#ln-fffff951","e":false,"i":"","n":"ln","t":"ln(file1: File, file2: File): File","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#ln_s-fffff951","e":false,"i":"","n":"ln_s","t":"ln_s(file1: File, file2: File): File","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#ls-fffffce5","e":false,"i":"","n":"ls","t":"ls(file: File): Iterator[File]","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#ls_r-fffffce5","e":false,"i":"","n":"ls_r","t":"ls_r(file: File): Iterator[File]","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#md5-9d6","e":false,"i":"","n":"md5","t":"md5(file: File): String","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#mkdir-20","e":false,"i":"","n":"mkdir","t":"mkdir(file: File): File","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#mkdirs-20","e":false,"i":"","n":"mkdirs","t":"mkdirs(file: File): File","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#mv-fffff951","e":false,"i":"","n":"mv","t":"mv(from: File, to: File): File","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#pwd-0","e":false,"i":"","n":"pwd","t":"pwd: File","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#rm-20","e":false,"i":"","n":"rm","t":"rm(file: File): File","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#sha1-9d6","e":false,"i":"","n":"sha1","t":"sha1(file: File): String","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#sha256-9d6","e":false,"i":"","n":"sha256","t":"sha256(file: File): String","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#sha512-9d6","e":false,"i":"","n":"sha512","t":"sha512(file: File): String","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#stat-347","e":false,"i":"","n":"stat","t":"stat(file: File): PosixFileAttributes","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#touch-20","e":false,"i":"","n":"touch","t":"touch(file: File): File","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#ungzip-fffff951","e":false,"i":"","n":"ungzip","t":"ungzip(gzipFile: File)(destination: File): File","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#unzip-fffff4ed","e":false,"i":"","n":"unzip","t":"unzip(zipFile: File)(destination: File, charset: Charset): File","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#zip-aec","e":false,"i":"","n":"zip","t":"zip(files: File*)(destination: File, compressionLevel: Int, charset: Charset): File","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$.html#~-0","e":false,"i":"","n":"~","t":"~: File","d":"better.files.Dsl","k":"def"},
{"l":"better/files/Dsl$$SymbolicOperations.html#","e":false,"i":"","n":"SymbolicOperations","t":"SymbolicOperations(val file: File)","d":"better.files.Dsl","k":"class"},
{"l":"better/files/Dsl$$SymbolicOperations.html#!-749","e":false,"i":"","n":"!","t":"!(implicit charset: Charset): String","d":"better.files.Dsl.SymbolicOperations","k":"def"},
{"l":"better/files/Dsl$$SymbolicOperations.html#!==-18f","e":false,"i":"","n":"!==","t":"!==(that: File): Boolean","d":"better.files.Dsl.SymbolicOperations","k":"def"},
{"l":"better/files/Dsl$$SymbolicOperations.html#/-fffff500","e":false,"i":"","n":"/","t":"/(f: File => File): File","d":"better.files.Dsl.SymbolicOperations","k":"def"},
{"l":"better/files/Dsl$$SymbolicOperations.html#<-fffff93d","e":false,"i":"","n":"<","t":"<(text: String, openOptions: OpenOptions, charset: Charset): File","d":"better.files.Dsl.SymbolicOperations","k":"def"},
{"l":"better/files/Dsl$$SymbolicOperations.html#<<-48","e":false,"i":"","n":"<<","t":"<<(line: String)(implicit charset: Charset): File","d":"better.files.Dsl.SymbolicOperations","k":"def"},
{"l":"better/files/Dsl$$SymbolicOperations.html#===-18f","e":false,"i":"","n":"===","t":"===(that: File): Boolean","d":"better.files.Dsl.SymbolicOperations","k":"def"},
{"l":"better/files/Dsl$$SymbolicOperations.html#>>:-48","e":false,"i":"","n":">>:","t":">>:(line: String)(implicit charset: Charset): File","d":"better.files.Dsl.SymbolicOperations","k":"def"},
{"l":"better/files/Dsl$$SymbolicOperations.html#>:-fffff93d","e":false,"i":"","n":"`>:`","t":"`>:`(text: String, openOptions: OpenOptions, charset: Charset): File","d":"better.files.Dsl.SymbolicOperations","k":"def"},
{"l":"better/files/Dsl$$SymbolicOperations.html#file-0","e":false,"i":"","n":"file","t":"file: File","d":"better.files.Dsl.SymbolicOperations","k":"val"},
{"l":"better/files/File.html#","e":false,"i":"","n":"File","t":"File extends Serializable","d":"better.files","k":"class"},
{"l":"better/files/File.html#/-fffff5ac","e":false,"i":"","n":"/","t":"/(child: String): File","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#/-e11","e":false,"i":"","n":"/","t":"/(child: Symbol): File","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#addPermission-ad6","e":false,"i":"","n":"addPermission","t":"addPermission(permission: PosixFilePermission, linkOptions: LinkOptions): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#append-48","e":false,"i":"","n":"append","t":"append(text: String, charset: Charset): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#appendByteArray-fffff77f","e":false,"i":"","n":"appendByteArray","t":"appendByteArray(bytes: Array[Byte]): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#appendBytes-6fb","e":false,"i":"","n":"appendBytes","t":"appendBytes(bytes: Iterator[Byte]): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#appendLine-48","e":false,"i":"","n":"appendLine","t":"appendLine(line: String, charset: Charset): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#appendLines-342","e":false,"i":"","n":"appendLines","t":"appendLines(lines: Seq[String], charset: Charset): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#appendLines-6a6","e":false,"i":"","n":"appendLines","t":"appendLines(lines: String*): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#appendText-48","e":false,"i":"","n":"appendText","t":"appendText(text: String, charset: Charset): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#asynchronousFileChannel-cb5","e":false,"i":"","n":"asynchronousFileChannel","t":"asynchronousFileChannel(openOptions: OpenOptions): Dispose[AsynchronousFileChannel]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#attributes-b8","e":false,"i":"","n":"attributes","t":"attributes(linkOptions: LinkOptions): BasicFileAttributes","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#bufferedReader-fffff4ee","e":false,"i":"","n":"bufferedReader","t":"bufferedReader(charset: Charset): Dispose[BufferedReader]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#bufferedWriter-499","e":false,"i":"","n":"bufferedWriter","t":"bufferedWriter(charset: Charset, openOptions: OpenOptions): Dispose[BufferedWriter]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#byteArray-0","e":false,"i":"","n":"byteArray","t":"byteArray: Array[Byte]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#bytes-0","e":false,"i":"","n":"bytes","t":"bytes: Iterator[Byte]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#canonicalFile-0","e":false,"i":"","n":"canonicalFile","t":"canonicalFile: File","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#canonicalPath-0","e":false,"i":"","n":"canonicalPath","t":"canonicalPath: String","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#changeExtensionTo-fffffda1","e":false,"i":"","n":"changeExtensionTo","t":"changeExtensionTo(extension: String, linkOptions: LinkOptions): File","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#chars-d2","e":false,"i":"","n":"chars","t":"chars(charset: Charset): Iterator[Char]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#checksum-7a4","e":false,"i":"","n":"checksum","t":"checksum(algorithm: MessageDigest, visitOptions: VisitOptions, linkOptions: LinkOptions): String","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#children-0","e":false,"i":"","n":"children","t":"children: Iterator[File]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#clear-6a6","e":false,"i":"","n":"clear","t":"clear(linkOptions: LinkOptions): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#collectChildren-af5","e":false,"i":"","n":"collectChildren","t":"collectChildren(matchFilter: File => Boolean, maxDepth: Int, visitOptions: VisitOptions): Iterator[File]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#contains-631","e":false,"i":"","n":"contains","t":"contains(file: File, strict: Boolean): Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#contentAsString-749","e":false,"i":"","n":"contentAsString","t":"contentAsString(charset: Charset): String","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#contentType-0","e":false,"i":"","n":"contentType","t":"contentType: Option[String]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#copyTo-fffff3c2","e":false,"i":"","n":"copyTo","t":"copyTo(destination: File, overwrite: Boolean): File","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#copyTo-fffff515","e":false,"i":"","n":"copyTo","t":"copyTo(destination: File, copyOptions: CopyOptions): File","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#copyToDirectory-fffff137","e":false,"i":"","n":"copyToDirectory","t":"copyToDirectory(directory: File, overwrite: Boolean, linkOptions: LinkOptions): File","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#createChild-b16","e":false,"i":"","n":"createChild","t":"createChild(child: String, asDirectory: Boolean, createParents: Boolean, attributes: Attributes, linkOptions: LinkOptions): File","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#createDirectories-d1b","e":false,"i":"","n":"createDirectories","t":"createDirectories(attributes: Attributes, linkOptions: LinkOptions): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#createDirectory-6a6","e":false,"i":"","n":"createDirectory","t":"createDirectory(attributes: Attributes): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#createDirectoryIfNotExists-fffff1bb","e":false,"i":"","n":"createDirectoryIfNotExists","t":"createDirectoryIfNotExists(createParents: Boolean, attributes: Attributes, linkOptions: LinkOptions): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#createFile-6a6","e":false,"i":"","n":"createFile","t":"createFile(attributes: Attributes): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#createFileIfNotExists-fffff1bb","e":false,"i":"","n":"createFileIfNotExists","t":"createFileIfNotExists(createParents: Boolean, attributes: Attributes, linkOptions: LinkOptions): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#createIfNotExists-fffff11b","e":false,"i":"","n":"createIfNotExists","t":"createIfNotExists(asDirectory: Boolean, createParents: Boolean, attributes: Attributes, linkOptions: LinkOptions): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#delete-fffff346","e":false,"i":"","n":"delete","t":"delete(swallowIOExceptions: Boolean, linkOption: LinkOptions): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#deleteOnExit-fffff346","e":false,"i":"","n":"deleteOnExit","t":"deleteOnExit(swallowIOExceptions: Boolean, linkOption: LinkOptions): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#digest-fffff0f1","e":false,"i":"","n":"digest","t":"digest(algorithm: MessageDigest, visitOptions: VisitOptions, linkOptions: LinkOptions): Array[Byte]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#dosAttributes-e12","e":false,"i":"","n":"dosAttributes","t":"dosAttributes(linkOptions: LinkOptions): DosFileAttributes","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#entries-0","e":false,"i":"","n":"entries","t":"entries: Iterator[File]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#exists-b15","e":false,"i":"","n":"exists","t":"exists(linkOptions: LinkOptions): Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#extension-b48","e":false,"i":"","n":"extension","t":"extension(includeDot: Boolean, includeAll: Boolean, toLowerCase: Boolean, linkOptions: LinkOptions): Option[String]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#fileChannel-fffff620","e":false,"i":"","n":"fileChannel","t":"fileChannel(openOptions: OpenOptions, attributes: Attributes): Dispose[FileChannel]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#fileInputStream-0","e":false,"i":"","n":"fileInputStream","t":"fileInputStream: Dispose[FileInputStream]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#fileOutputStream-fffffd6a","e":false,"i":"","n":"fileOutputStream","t":"fileOutputStream(append: Boolean): Dispose[FileOutputStream]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#fileReader-0","e":false,"i":"","n":"fileReader","t":"fileReader: Dispose[FileReader]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#fileSystem-0","e":false,"i":"","n":"fileSystem","t":"fileSystem: FileSystem","d":"better.files.File","k":"val"},
{"l":"better/files/File.html#fileWriter-fffffd6a","e":false,"i":"","n":"fileWriter","t":"fileWriter(append: Boolean): Dispose[FileWriter]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#glob-fffff6ca","e":false,"i":"","n":"glob","t":"glob(pattern: String, includePath: Boolean, maxDepth: Int, syntax: PathMatcherSyntax, visitOptions: VisitOptions): Iterator[File]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#globRegex-fffffa4a","e":false,"i":"","n":"globRegex","t":"globRegex(pattern: Regex, includePath: Boolean, maxDepth: Int, visitOptions: VisitOptions): Iterator[File]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#group-118","e":false,"i":"","n":"group","t":"group(linkOptions: LinkOptions): GroupPrincipal","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#groupName-a90","e":false,"i":"","n":"groupName","t":"groupName(linkOptions: LinkOptions): String","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#gzipInputStream-fffffbb1","e":false,"i":"","n":"gzipInputStream","t":"gzipInputStream(bufferSize: Int): Dispose[GZIPInputStream]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#gzipOutputStream-4f1","e":false,"i":"","n":"gzipOutputStream","t":"gzipOutputStream(bufferSize: Int, syncFlush: Boolean, append: Boolean): Dispose[GZIPOutputStream]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#gzipTo-6db","e":false,"i":"","n":"gzipTo","t":"gzipTo(destination: File, bufferSize: Int, syncFlush: Boolean, append: Boolean): File","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#hasExtension-b15","e":false,"i":"","n":"hasExtension","t":"hasExtension(linkOptions: LinkOptions): Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#inputStream-cb5","e":false,"i":"","n":"inputStream","t":"inputStream(openOptions: OpenOptions): Dispose[InputStream]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#isChildOf-18f","e":false,"i":"","n":"isChildOf","t":"isChildOf(parent: File): Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#isDirectory-b15","e":false,"i":"","n":"isDirectory","t":"isDirectory(linkOptions: LinkOptions): Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#isEmpty-b15","e":false,"i":"","n":"isEmpty","t":"isEmpty(linkOptions: LinkOptions): Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#isExecutable-0","e":false,"i":"","n":"isExecutable","t":"isExecutable: Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#isGroupExecutable-b15","e":false,"i":"","n":"isGroupExecutable","t":"isGroupExecutable(linkOptions: LinkOptions): Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#isGroupReadable-b15","e":false,"i":"","n":"isGroupReadable","t":"isGroupReadable(linkOptions: LinkOptions): Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#isGroupWritable-b15","e":false,"i":"","n":"isGroupWritable","t":"isGroupWritable(linkOptions: LinkOptions): Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#isHidden-0","e":false,"i":"","n":"isHidden","t":"isHidden: Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#isLocked-fffff9e2","e":false,"i":"","n":"isLocked","t":"isLocked(mode: RandomAccessMode, position: Long, size: Long, isShared: Boolean, linkOptions: LinkOptions): Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#isOthersExecutable-b15","e":false,"i":"","n":"isOthersExecutable","t":"isOthersExecutable(linkOptions: LinkOptions): Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#isOthersReadable-b15","e":false,"i":"","n":"isOthersReadable","t":"isOthersReadable(linkOptions: LinkOptions): Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#isOthersWritable-b15","e":false,"i":"","n":"isOthersWritable","t":"isOthersWritable(linkOptions: LinkOptions): Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#isOwnerExecutable-b15","e":false,"i":"","n":"isOwnerExecutable","t":"isOwnerExecutable(linkOptions: LinkOptions): Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#isOwnerReadable-b15","e":false,"i":"","n":"isOwnerReadable","t":"isOwnerReadable(linkOptions: LinkOptions): Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#isOwnerWritable-b15","e":false,"i":"","n":"isOwnerWritable","t":"isOwnerWritable(linkOptions: LinkOptions): Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#isParentOf-18f","e":false,"i":"","n":"isParentOf","t":"isParentOf(child: File): Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#isReadLocked-fffff988","e":false,"i":"","n":"isReadLocked","t":"isReadLocked(position: Long, size: Long, isShared: Boolean): Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#isReadable-0","e":false,"i":"","n":"isReadable","t":"isReadable: Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#isRegularFile-b15","e":false,"i":"","n":"isRegularFile","t":"isRegularFile(linkOptions: LinkOptions): Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#isSameContentAs-18f","e":false,"i":"","n":"isSameContentAs","t":"isSameContentAs(that: File): Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#isSameFileAs-18f","e":false,"i":"","n":"isSameFileAs","t":"isSameFileAs(that: File): Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#isSamePathAs-18f","e":false,"i":"","n":"isSamePathAs","t":"isSamePathAs(that: File): Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#isSiblingOf-18f","e":false,"i":"","n":"isSiblingOf","t":"isSiblingOf(sibling: File): Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#isSimilarContentAs-18f","e":false,"i":"","n":"isSimilarContentAs","t":"isSimilarContentAs(that: File): Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#isSymbolicLink-0","e":false,"i":"","n":"isSymbolicLink","t":"isSymbolicLink: Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#isWritable-0","e":false,"i":"","n":"isWritable","t":"isWritable: Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#isWriteLocked-fffff988","e":false,"i":"","n":"isWriteLocked","t":"isWriteLocked(position: Long, size: Long, isShared: Boolean): Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#lastModifiedTime-fffffd21","e":false,"i":"","n":"lastModifiedTime","t":"lastModifiedTime(linkOptions: LinkOptions): Instant","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#lineCount-6c3","e":false,"i":"","n":"lineCount","t":"lineCount(charset: Charset): Int","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#lineIterator-d2","e":false,"i":"","n":"lineIterator","t":"lineIterator(charset: Charset): Iterator[String]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#lines-cd6","e":false,"i":"","n":"lines","t":"lines(charset: Charset): Iterable[String]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#linkTo-fffff137","e":false,"i":"","n":"linkTo","t":"linkTo(destination: File, symbolic: Boolean, attributes: Attributes): File","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#list-af5","e":false,"i":"","n":"list","t":"list(filter: File => Boolean, maxDepth: Int, visitOptions: VisitOptions): Iterator[File]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#list-0","e":false,"i":"","n":"list","t":"list: Iterator[File]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#listRecursively-fffffd6b","e":false,"i":"","n":"listRecursively","t":"listRecursively(visitOptions: VisitOptions): Iterator[File]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#listRelativePaths-fffffd6b","e":false,"i":"","n":"listRelativePaths","t":"listRelativePaths(visitOptions: VisitOptions): Iterator[Path]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#loadBytes-0","e":false,"i":"","n":"loadBytes","t":"loadBytes: Array[Byte]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#md5-fffff17b","e":false,"i":"","n":"md5","t":"md5(visitOptions: VisitOptions, linkOptions: LinkOptions): String","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#moveTo-fffff515","e":false,"i":"","n":"moveTo","t":"moveTo(destination: File, copyOptions: CopyOptions): File","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#moveToDirectory-fffff515","e":false,"i":"","n":"moveToDirectory","t":"moveToDirectory(directory: File, linkOptions: LinkOptions): File","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#name-0","e":false,"i":"","n":"name","t":"name: String","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#nameOption-0","e":false,"i":"","n":"nameOption","t":"nameOption: Option[String]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#nameWithoutExtension-0","e":false,"i":"","n":"nameWithoutExtension","t":"nameWithoutExtension: String","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#nameWithoutExtension-fffff9f0","e":false,"i":"","n":"nameWithoutExtension","t":"nameWithoutExtension(includeAll: Boolean, linkOptions: LinkOptions): String","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#newAsynchronousFileChannel-fffff15c","e":false,"i":"","n":"newAsynchronousFileChannel","t":"newAsynchronousFileChannel(openOptions: OpenOptions): AsynchronousFileChannel","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#newBufferedReader-582","e":false,"i":"","n":"newBufferedReader","t":"newBufferedReader(charset: Charset): BufferedReader","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#newBufferedWriter-fffff21d","e":false,"i":"","n":"newBufferedWriter","t":"newBufferedWriter(charset: Charset, openOptions: OpenOptions): BufferedWriter","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#newFileChannel-fffffd39","e":false,"i":"","n":"newFileChannel","t":"newFileChannel(openOptions: OpenOptions, attributes: Attributes): FileChannel","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#newFileInputStream-0","e":false,"i":"","n":"newFileInputStream","t":"newFileInputStream: FileInputStream","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#newFileOutputStream-fffffcf9","e":false,"i":"","n":"newFileOutputStream","t":"newFileOutputStream(append: Boolean): FileOutputStream","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#newFileReader-0","e":false,"i":"","n":"newFileReader","t":"newFileReader: FileReader","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#newFileWriter-fffff38b","e":false,"i":"","n":"newFileWriter","t":"newFileWriter(append: Boolean): FileWriter","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#newGzipInputStream-dfc","e":false,"i":"","n":"newGzipInputStream","t":"newGzipInputStream(bufferSize: Int): GZIPInputStream","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#newGzipOutputStream-14f","e":false,"i":"","n":"newGzipOutputStream","t":"newGzipOutputStream(bufferSize: Int, syncFlush: Boolean, append: Boolean): GZIPOutputStream","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#newInputStream-443","e":false,"i":"","n":"newInputStream","t":"newInputStream(openOptions: OpenOptions): InputStream","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#newOutputStream-fffffaa8","e":false,"i":"","n":"newOutputStream","t":"newOutputStream(openOptions: OpenOptions): OutputStream","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#newPrintWriter-279","e":false,"i":"","n":"newPrintWriter","t":"newPrintWriter(autoFlush: Boolean, openOptions: OpenOptions): PrintWriter","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#newRandomAccess-764","e":false,"i":"","n":"newRandomAccess","t":"newRandomAccess(mode: RandomAccessMode): RandomAccessFile","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#newScanner-fa","e":false,"i":"","n":"newScanner","t":"newScanner(splitter: StringSplitter, charset: Charset): Scanner","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#newWatchService-0","e":false,"i":"","n":"newWatchService","t":"newWatchService: WatchService","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#newZipInputStream-51a","e":false,"i":"","n":"newZipInputStream","t":"newZipInputStream(charset: Charset): ZipInputStream","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#newZipOutputStream-f66","e":false,"i":"","n":"newZipOutputStream","t":"newZipOutputStream(openOptions: OpenOptions, charset: Charset): ZipOutputStream","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#nonEmpty-b15","e":false,"i":"","n":"nonEmpty","t":"nonEmpty(linkOptions: LinkOptions): Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#notExists-b15","e":false,"i":"","n":"notExists","t":"notExists(linkOptions: LinkOptions): Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#outputStream-cb5","e":false,"i":"","n":"outputStream","t":"outputStream(openOptions: OpenOptions): Dispose[OutputStream]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#overwrite-fffff93d","e":false,"i":"","n":"overwrite","t":"overwrite(text: String, openOptions: OpenOptions, charset: Charset): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#owner-6da","e":false,"i":"","n":"owner","t":"owner(linkOptions: LinkOptions): UserPrincipal","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#ownerName-a90","e":false,"i":"","n":"ownerName","t":"ownerName(linkOptions: LinkOptions): String","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#parent-0","e":false,"i":"","n":"parent","t":"parent: File","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#parentOption-0","e":false,"i":"","n":"parentOption","t":"parentOption: Option[File]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#path-0","e":false,"i":"","n":"path","t":"path: Path","d":"better.files.File","k":"val"},
{"l":"better/files/File.html#pathAsString-0","e":false,"i":"","n":"pathAsString","t":"pathAsString: String","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#pathMatcher-fffffbd1","e":false,"i":"","n":"pathMatcher","t":"pathMatcher(syntax: PathMatcherSyntax, includePath: Boolean)(pattern: String): PathMatcher","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#permissions-719","e":false,"i":"","n":"permissions","t":"permissions(linkOptions: LinkOptions): Set[PosixFilePermission]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#permissionsAsString-a90","e":false,"i":"","n":"permissionsAsString","t":"permissionsAsString(linkOptions: LinkOptions): String","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#posixAttributes-e4d","e":false,"i":"","n":"posixAttributes","t":"posixAttributes(linkOptions: LinkOptions): PosixFileAttributes","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#printLines-fffffe6b","e":false,"i":"","n":"printLines","t":"printLines(lines: IterableOnce[_], openOptions: OpenOptions): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#printWriter-fffffc15","e":false,"i":"","n":"printWriter","t":"printWriter(autoFlush: Boolean, openOptions: OpenOptions): Dispose[PrintWriter]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#randomAccess-fffffbaf","e":false,"i":"","n":"randomAccess","t":"randomAccess(mode: RandomAccessMode): Dispose[RandomAccessFile]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#readDeserialized-7f7","e":false,"i":"","n":"readDeserialized","t":"readDeserialized[A](classLoaderOverride: Option[ClassLoader], bufferSize: Int, openOptions: OpenOptions): A","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#register-654","e":false,"i":"","n":"register","t":"register(service: WatchService, events: Events): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#relativize-a82","e":false,"i":"","n":"relativize","t":"relativize(destination: File): Path","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#removePermission-ad6","e":false,"i":"","n":"removePermission","t":"removePermission(permission: PosixFilePermission, linkOptions: LinkOptions): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#renameTo-fffff5ac","e":false,"i":"","n":"renameTo","t":"renameTo(newName: String): File","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#resourcePathAsString-0","e":false,"i":"","n":"resourcePathAsString","t":"resourcePathAsString: String","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#root-0","e":false,"i":"","n":"root","t":"root: File","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#scanner-11b","e":false,"i":"","n":"scanner","t":"scanner(splitter: StringSplitter, charset: Charset): Dispose[Scanner]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#setGroup-fffffda1","e":false,"i":"","n":"setGroup","t":"setGroup(group: String, linkOptions: LinkOptions): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#setOwner-fffff5ac","e":false,"i":"","n":"setOwner","t":"setOwner(owner: String): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#setPermissions-fffffd03","e":false,"i":"","n":"setPermissions","t":"setPermissions(permissions: Set[PosixFilePermission]): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#sha1-fffff17b","e":false,"i":"","n":"sha1","t":"sha1(visitOptions: VisitOptions, linkOptions: LinkOptions): String","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#sha256-fffff17b","e":false,"i":"","n":"sha256","t":"sha256(visitOptions: VisitOptions, linkOptions: LinkOptions): String","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#sha512-fffff17b","e":false,"i":"","n":"sha512","t":"sha512(visitOptions: VisitOptions, linkOptions: LinkOptions): String","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#sibling-fffff5ac","e":false,"i":"","n":"sibling","t":"sibling(name: String): File","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#siblings-0","e":false,"i":"","n":"siblings","t":"siblings: Iterator[File]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#size-fffffe0f","e":false,"i":"","n":"size","t":"size(returnZeroIfMissing: Boolean, visitOptions: VisitOptions): Long","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#streamedUnzip-fffffebc","e":false,"i":"","n":"streamedUnzip","t":"streamedUnzip(destinationDirectory: File, charset: Charset): File","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#symbolicLink-0","e":false,"i":"","n":"symbolicLink","t":"symbolicLink: Option[File]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#symbolicLinkTo-fffff515","e":false,"i":"","n":"symbolicLinkTo","t":"symbolicLinkTo(destination: File, attributes: Attributes): File","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#testPermission-745","e":false,"i":"","n":"testPermission","t":"testPermission(permission: PosixFilePermission, linkOptions: LinkOptions): Boolean","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#toJava-0","e":false,"i":"","n":"toJava","t":"toJava: File","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#toTemporary-0","e":false,"i":"","n":"toTemporary","t":"toTemporary: Dispose[File]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#tokens-fffff8c5","e":false,"i":"","n":"tokens","t":"tokens(splitter: StringSplitter, charset: Charset): Iterator[String]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#touch-af","e":false,"i":"","n":"touch","t":"touch(time: Instant, attributes: Attributes, linkOptions: LinkOptions): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#unGzipTo-5f9","e":false,"i":"","n":"unGzipTo","t":"unGzipTo(destination: File, append: Boolean, bufferSize: Int): File","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#unzip-39c","e":false,"i":"","n":"unzip","t":"unzip(zipFilter: ZipEntry => Boolean, charset: Charset): File","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#unzipTo-20d","e":false,"i":"","n":"unzipTo","t":"unzipTo(destination: File, zipFilter: ZipEntry => Boolean, charset: Charset): File","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#update-fffff1ae","e":false,"i":"","n":"update","t":"update(attribute: String, value: Any, linkOptions: LinkOptions): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#uri-0","e":false,"i":"","n":"uri","t":"uri: URI","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#url-0","e":false,"i":"","n":"url","t":"url: URL","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#usingLock-d50","e":false,"i":"","n":"usingLock","t":"usingLock[U](mode: RandomAccessMode)(f: FileChannel => U): U","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#verifiedExists-fffff7e8","e":false,"i":"","n":"verifiedExists","t":"verifiedExists(linkOptions: LinkOptions): Option[Boolean]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#walk-fffffe64","e":false,"i":"","n":"walk","t":"walk(maxDepth: Int, visitOptions: VisitOptions): Iterator[File]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#watchService-0","e":false,"i":"","n":"watchService","t":"watchService: Dispose[WatchService]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#write-fffff93d","e":false,"i":"","n":"write","t":"write(text: String, openOptions: OpenOptions, charset: Charset): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#writeByteArray-c34","e":false,"i":"","n":"writeByteArray","t":"writeByteArray(bytes: Array[Byte], openOptions: OpenOptions): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#writeBytes-fffffab0","e":false,"i":"","n":"writeBytes","t":"writeBytes(bytes: Iterator[Byte], openOptions: OpenOptions): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#writeSerialized-fffff0ba","e":false,"i":"","n":"writeSerialized","t":"writeSerialized(obj: Serializable, bufferSize: Int, openOptions: OpenOptions): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#writeText-fffff93d","e":false,"i":"","n":"writeText","t":"writeText(text: String, openOptions: OpenOptions, charset: Charset): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#zip-fffff9c6","e":false,"i":"","n":"zip","t":"zip(compressionLevel: Int, charset: Charset): File","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#zipIn-fffff17c","e":false,"i":"","n":"zipIn","t":"zipIn(files: Iterator[File], compressionLevel: Int, charset: Charset): File.this.type","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#zipInputStream-fffff4ee","e":false,"i":"","n":"zipInputStream","t":"zipInputStream(charset: Charset): Dispose[ZipInputStream]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#zipOutputStream-a99","e":false,"i":"","n":"zipOutputStream","t":"zipOutputStream(openOptions: OpenOptions, charset: Charset): Dispose[ZipOutputStream]","d":"better.files.File","k":"def"},
{"l":"better/files/File.html#zipTo-fffff0f7","e":false,"i":"","n":"zipTo","t":"zipTo(destination: File, compressionLevel: Int, charset: Charset): File","d":"better.files.File","k":"def"},
{"l":"better/files/File$.html#","e":false,"i":"","n":"File","t":"File","d":"better.files","k":"object"},
{"l":"better/files/File$.html#Attributes-0","e":false,"i":"","n":"Attributes","t":"Attributes = Seq[FileAttribute[_]]","d":"better.files.File","k":"type"},
{"l":"better/files/File$.html#CopyOptions-0","e":false,"i":"","n":"CopyOptions","t":"CopyOptions = Seq[CopyOption]","d":"better.files.File","k":"type"},
{"l":"better/files/File$.html#Events-0","e":false,"i":"","n":"Events","t":"Events = Seq[Kind[_]]","d":"better.files.File","k":"type"},
{"l":"better/files/File$.html#LinkOptions-0","e":false,"i":"","n":"LinkOptions","t":"LinkOptions = Seq[LinkOption]","d":"better.files.File","k":"type"},
{"l":"better/files/File$.html#OpenOptions-0","e":false,"i":"","n":"OpenOptions","t":"OpenOptions = Seq[OpenOption]","d":"better.files.File","k":"type"},
{"l":"better/files/File$.html#Order-0","e":false,"i":"","n":"Order","t":"Order = Ordering[File]","d":"better.files.File","k":"type"},
{"l":"better/files/File$.html#VisitOptions-0","e":false,"i":"","n":"VisitOptions","t":"VisitOptions = Seq[FileVisitOption]","d":"better.files.File","k":"type"},
{"l":"better/files/File$.html#apply-240","e":false,"i":"","n":"apply","t":"apply(path: Path): File","d":"better.files.File","k":"def"},
{"l":"better/files/File$.html#apply-fffffda1","e":false,"i":"","n":"apply","t":"apply(path: String, fragments: String*): File","d":"better.files.File","k":"def"},
{"l":"better/files/File$.html#apply-fffffe10","e":false,"i":"","n":"apply","t":"apply(anchor: File, path: String, fragments: String*): File","d":"better.files.File","k":"def"},
{"l":"better/files/File$.html#apply-fffff1ff","e":false,"i":"","n":"apply","t":"apply(url: URL): File","d":"better.files.File","k":"def"},
{"l":"better/files/File$.html#apply-fffffba2","e":false,"i":"","n":"apply","t":"apply(uri: URI): File","d":"better.files.File","k":"def"},
{"l":"better/files/File$.html#currentWorkingDirectory-0","e":false,"i":"","n":"currentWorkingDirectory","t":"currentWorkingDirectory: File","d":"better.files.File","k":"def"},
{"l":"better/files/File$.html#home-0","e":false,"i":"","n":"home","t":"home: File","d":"better.files.File","k":"def"},
{"l":"better/files/File$.html#newTemporaryDirectory-944","e":false,"i":"","n":"newTemporaryDirectory","t":"newTemporaryDirectory(prefix: String, parent: Option[File], attributes: Attributes): File","d":"better.files.File","k":"def"},
{"l":"better/files/File$.html#newTemporaryFile-9bf","e":false,"i":"","n":"newTemporaryFile","t":"newTemporaryFile(prefix: String, suffix: String, parent: Option[File], attributes: Attributes): File","d":"better.files.File","k":"def"},
{"l":"better/files/File$.html#numberOfOpenFileDescriptors-644","e":false,"i":"","n":"numberOfOpenFileDescriptors","t":"numberOfOpenFileDescriptors(): Long","d":"better.files.File","k":"def"},
{"l":"better/files/File$.html#root-0","e":false,"i":"","n":"root","t":"root: File","d":"better.files.File","k":"def"},
{"l":"better/files/File$.html#roots-0","e":false,"i":"","n":"roots","t":"roots: Iterable[File]","d":"better.files.File","k":"def"},
{"l":"better/files/File$.html#temp-0","e":false,"i":"","n":"temp","t":"temp: File","d":"better.files.File","k":"def"},
{"l":"better/files/File$.html#temporaryDirectory-fffffd57","e":false,"i":"","n":"temporaryDirectory","t":"temporaryDirectory(prefix: String, parent: Option[File], attributes: Attributes): Dispose[File]","d":"better.files.File","k":"def"},
{"l":"better/files/File$.html#temporaryFile-fffff36d","e":false,"i":"","n":"temporaryFile","t":"temporaryFile[U](prefix: String, suffix: String, parent: Option[File], attributes: Attributes): Dispose[File]","d":"better.files.File","k":"def"},
{"l":"better/files/File$.html#usingTemporaryDirectory-d9f","e":false,"i":"","n":"usingTemporaryDirectory","t":"usingTemporaryDirectory[U](prefix: String, parent: Option[File], attributes: Attributes)(f: File => U): Unit","d":"better.files.File","k":"def"},
{"l":"better/files/File$.html#usingTemporaryFile-51a","e":false,"i":"","n":"usingTemporaryFile","t":"usingTemporaryFile[U](prefix: String, suffix: String, parent: Option[File], attributes: Attributes)(f: File => U): Unit","d":"better.files.File","k":"def"},
{"l":"better/files/File$$Attributes$.html#","e":false,"i":"","n":"Attributes","t":"Attributes","d":"better.files.File","k":"object"},
{"l":"better/files/File$$Attributes$.html#default-0","e":false,"i":"","n":"default","t":"default: Attributes","d":"better.files.File.Attributes","k":"val"},
{"l":"better/files/File$$CopyOptions$.html#","e":false,"i":"","n":"CopyOptions","t":"CopyOptions","d":"better.files.File","k":"object"},
{"l":"better/files/File$$CopyOptions$.html#apply-98b","e":false,"i":"","n":"apply","t":"apply(overwrite: Boolean): CopyOptions","d":"better.files.File.CopyOptions","k":"def"},
{"l":"better/files/File$$CopyOptions$.html#atomically-0","e":false,"i":"","n":"atomically","t":"atomically: CopyOptions","d":"better.files.File.CopyOptions","k":"val"},
{"l":"better/files/File$$CopyOptions$.html#default-0","e":false,"i":"","n":"default","t":"default: CopyOptions","d":"better.files.File.CopyOptions","k":"val"},
{"l":"better/files/File$$Events$.html#","e":false,"i":"","n":"Events","t":"Events","d":"better.files.File","k":"object"},
{"l":"better/files/File$$Events$.html#all-0","e":false,"i":"","n":"all","t":"all: Events","d":"better.files.File.Events","k":"val"},
{"l":"better/files/File$$Events$.html#default-0","e":false,"i":"","n":"default","t":"default: Events","d":"better.files.File.Events","k":"val"},
{"l":"better/files/File$$LinkOptions$.html#","e":false,"i":"","n":"LinkOptions","t":"LinkOptions","d":"better.files.File","k":"object"},
{"l":"better/files/File$$LinkOptions$.html#default-0","e":false,"i":"","n":"default","t":"default: LinkOptions","d":"better.files.File.LinkOptions","k":"val"},
{"l":"better/files/File$$LinkOptions$.html#follow-0","e":false,"i":"","n":"follow","t":"follow: LinkOptions","d":"better.files.File.LinkOptions","k":"val"},
{"l":"better/files/File$$LinkOptions$.html#noFollow-0","e":false,"i":"","n":"noFollow","t":"noFollow: LinkOptions","d":"better.files.File.LinkOptions","k":"val"},
{"l":"better/files/File$$Monitor.html#","e":false,"i":"","n":"Monitor","t":"Monitor extends AutoCloseable","d":"better.files.File","k":"trait"},
{"l":"better/files/File$$Monitor.html#onCreate-fffffea2","e":false,"i":"","n":"onCreate","t":"onCreate(file: File, count: Int): Unit","d":"better.files.File.Monitor","k":"def"},
{"l":"better/files/File$$Monitor.html#onDelete-fffffea2","e":false,"i":"","n":"onDelete","t":"onDelete(file: File, count: Int): Unit","d":"better.files.File.Monitor","k":"def"},
{"l":"better/files/File$$Monitor.html#onEvent-fffff357","e":false,"i":"","n":"onEvent","t":"onEvent(eventType: Kind[Path], file: File, count: Int): Unit","d":"better.files.File.Monitor","k":"def"},
{"l":"better/files/File$$Monitor.html#onException-4b8","e":false,"i":"","n":"onException","t":"onException(exception: Throwable): Unit","d":"better.files.File.Monitor","k":"def"},
{"l":"better/files/File$$Monitor.html#onModify-fffffea2","e":false,"i":"","n":"onModify","t":"onModify(file: File, count: Int): Unit","d":"better.files.File.Monitor","k":"def"},
{"l":"better/files/File$$Monitor.html#onUnknownEvent-1c3","e":false,"i":"","n":"onUnknownEvent","t":"onUnknownEvent(event: WatchEvent[_]): Unit","d":"better.files.File.Monitor","k":"def"},
{"l":"better/files/File$$Monitor.html#root-0","e":false,"i":"","n":"root","t":"root: File","d":"better.files.File.Monitor","k":"val"},
{"l":"better/files/File$$Monitor.html#start-12","e":false,"i":"","n":"start","t":"start()(implicit executionContext: ExecutionContext): Unit","d":"better.files.File.Monitor","k":"def"},
{"l":"better/files/File$$Monitor.html#stop-94c","e":false,"i":"","n":"stop","t":"stop(): Unit","d":"better.files.File.Monitor","k":"def"},
{"l":"better/files/File$$OpenOptions$.html#","e":false,"i":"","n":"OpenOptions","t":"OpenOptions","d":"better.files.File","k":"object"},
{"l":"better/files/File$$OpenOptions$.html#append-0","e":false,"i":"","n":"append","t":"append: OpenOptions","d":"better.files.File.OpenOptions","k":"val"},
{"l":"better/files/File$$OpenOptions$.html#default-0","e":false,"i":"","n":"default","t":"default: OpenOptions","d":"better.files.File.OpenOptions","k":"val"},
{"l":"better/files/File$$Order$.html#","e":false,"i":"","n":"Order","t":"Order","d":"better.files.File","k":"object"},
{"l":"better/files/File$$Order$.html#byDepth-0","e":false,"i":"","n":"byDepth","t":"byDepth: Order","d":"better.files.File.Order","k":"val"},
{"l":"better/files/File$$Order$.html#byDirectoriesFirst-0","e":false,"i":"","n":"byDirectoriesFirst","t":"byDirectoriesFirst: Order","d":"better.files.File.Order","k":"val"},
{"l":"better/files/File$$Order$.html#byDirectoriesLast-0","e":false,"i":"","n":"byDirectoriesLast","t":"byDirectoriesLast: Order","d":"better.files.File.Order","k":"val"},
{"l":"better/files/File$$Order$.html#byModificationTime-0","e":false,"i":"","n":"byModificationTime","t":"byModificationTime: Order","d":"better.files.File.Order","k":"val"},
{"l":"better/files/File$$Order$.html#byName-0","e":false,"i":"","n":"byName","t":"byName: Order","d":"better.files.File.Order","k":"val"},
{"l":"better/files/File$$Order$.html#bySize-0","e":false,"i":"","n":"bySize","t":"bySize: Order","d":"better.files.File.Order","k":"val"},
{"l":"better/files/File$$Order$.html#default-0","e":false,"i":"","n":"default","t":"default: Order","d":"better.files.File.Order","k":"val"},
{"l":"better/files/File$$PathMatcherSyntax.html#","e":false,"i":"","n":"PathMatcherSyntax","t":"PathMatcherSyntax(name: String)","d":"better.files.File","k":"class"},
{"l":"better/files/File$$PathMatcherSyntax.html#apply-fffff297","e":false,"i":"","n":"apply","t":"apply(file: File, pattern: String, includePath: Boolean): PathMatcher","d":"better.files.File.PathMatcherSyntax","k":"def"},
{"l":"better/files/File$$PathMatcherSyntax.html#escapePath-fffff2ca","e":false,"i":"","n":"escapePath","t":"escapePath(path: String): String","d":"better.files.File.PathMatcherSyntax","k":"def"},
{"l":"better/files/File$$PathMatcherSyntax$.html#","e":false,"i":"","n":"PathMatcherSyntax","t":"PathMatcherSyntax","d":"better.files.File","k":"object"},
{"l":"better/files/File$$PathMatcherSyntax$.html#default-0","e":false,"i":"","n":"default","t":"default: PathMatcherSyntax","d":"better.files.File.PathMatcherSyntax","k":"val"},
{"l":"better/files/File$$PathMatcherSyntax$.html#glob-0","e":false,"i":"","n":"glob","t":"glob: PathMatcherSyntax","d":"better.files.File.PathMatcherSyntax","k":"val"},
{"l":"better/files/File$$PathMatcherSyntax$.html#regex-0","e":false,"i":"","n":"regex","t":"regex: PathMatcherSyntax","d":"better.files.File.PathMatcherSyntax","k":"val"},
{"l":"better/files/File$$RandomAccessMode.html#","e":false,"i":"","n":"RandomAccessMode","t":"RandomAccessMode","d":"better.files.File","k":"class"},
{"l":"better/files/File$$RandomAccessMode.html#value-0","e":false,"i":"","n":"value","t":"value: String","d":"better.files.File.RandomAccessMode","k":"val"},
{"l":"better/files/File$$RandomAccessMode$.html#","e":false,"i":"","n":"RandomAccessMode","t":"RandomAccessMode","d":"better.files.File","k":"object"},
{"l":"better/files/File$$RandomAccessMode$.html#read-0","e":false,"i":"","n":"read","t":"read: RandomAccessMode","d":"better.files.File.RandomAccessMode","k":"val"},
{"l":"better/files/File$$RandomAccessMode$.html#readWrite-0","e":false,"i":"","n":"readWrite","t":"readWrite: RandomAccessMode","d":"better.files.File.RandomAccessMode","k":"val"},
{"l":"better/files/File$$RandomAccessMode$.html#readWriteContentSynchronous-0","e":false,"i":"","n":"readWriteContentSynchronous","t":"readWriteContentSynchronous: RandomAccessMode","d":"better.files.File.RandomAccessMode","k":"val"},
{"l":"better/files/File$$RandomAccessMode$.html#readWriteMetadataSynchronous-0","e":false,"i":"","n":"readWriteMetadataSynchronous","t":"readWriteMetadataSynchronous: RandomAccessMode","d":"better.files.File.RandomAccessMode","k":"val"},
{"l":"better/files/File$$VisitOptions$.html#","e":false,"i":"","n":"VisitOptions","t":"VisitOptions","d":"better.files.File","k":"object"},
{"l":"better/files/File$$VisitOptions$.html#default-0","e":false,"i":"","n":"default","t":"default: VisitOptions","d":"better.files.File.VisitOptions","k":"val"},
{"l":"better/files/File$$VisitOptions$.html#follow-0","e":false,"i":"","n":"follow","t":"follow: VisitOptions","d":"better.files.File.VisitOptions","k":"val"},
{"l":"better/files/FileMonitor.html#","e":false,"i":"","n":"FileMonitor","t":"FileMonitor(val root: File, maxDepth: Int) extends Monitor","d":"better.files","k":"class"},
{"l":"better/files/FileMonitor.html#root-0","e":false,"i":"","n":"root","t":"root: File","d":"better.files.FileMonitor","k":"val"},
{"l":"better/files/FileMonitor.html#<init>-338","e":false,"i":"","n":"this","t":"this(root: File, recursive: Boolean)","d":"better.files.FileMonitor","k":"def"},
{"l":"better/files/Implicits.html#","e":false,"i":"","n":"Implicits","t":"Implicits extends Implicits with Implicits with Implicits","d":"better.files","k":"trait"},
{"l":"better/files/Implicits.html#BufferedReaderExtensions-fffff8ed","e":false,"i":"","n":"BufferedReaderExtensions","t":"BufferedReaderExtensions(reader: BufferedReader): BufferedReaderExtensions","d":"better.files.Implicits","k":"def"},
{"l":"better/files/Implicits.html#DigestInputStreamExtensions-fffffe89","e":false,"i":"","n":"DigestInputStreamExtensions","t":"DigestInputStreamExtensions(in: DigestInputStream): DigestInputStreamExtensions","d":"better.files.Implicits","k":"def"},
{"l":"better/files/Implicits.html#DisposeableExtensions-fffff0c9","e":false,"i":"","n":"DisposeableExtensions","t":"DisposeableExtensions[A : Disposable](resource: A): DisposeableExtensions[A]","d":"better.files.Implicits","k":"def"},
{"l":"better/files/Implicits.html#FileChannelExtensions-975","e":false,"i":"","n":"FileChannelExtensions","t":"FileChannelExtensions(fc: FileChannel): FileChannelExtensions","d":"better.files.Implicits","k":"def"},
{"l":"better/files/Implicits.html#FileExtensions-26d","e":false,"i":"","n":"FileExtensions","t":"FileExtensions(file: File): FileExtensions","d":"better.files.Implicits","k":"def"},
{"l":"better/files/Implicits.html#InputStreamExtensions-ef7","e":false,"i":"","n":"InputStreamExtensions","t":"InputStreamExtensions(in: InputStream): InputStreamExtensions","d":"better.files.Implicits","k":"def"},
{"l":"better/files/Implicits.html#IteratorExtensions-fffff672","e":false,"i":"","n":"IteratorExtensions","t":"IteratorExtensions[A](it: Iterator[A]): IteratorExtensions[A]","d":"better.files.Implicits","k":"def"},
{"l":"better/files/Implicits.html#JStreamExtensions-fffffda6","e":false,"i":"","n":"JStreamExtensions","t":"JStreamExtensions[A](stream: Stream[A]): JStreamExtensions[A]","d":"better.files.Implicits","k":"def"},
{"l":"better/files/Implicits.html#ObjectInputStreamExtensions-fffffc39","e":false,"i":"","n":"ObjectInputStreamExtensions","t":"ObjectInputStreamExtensions(ois: ObjectInputStream): ObjectInputStreamExtensions","d":"better.files.Implicits","k":"def"},
{"l":"better/files/Implicits.html#ObjectOutputStreamExtensions-12d","e":false,"i":"","n":"ObjectOutputStreamExtensions","t":"ObjectOutputStreamExtensions(oos: ObjectOutputStream): ObjectOutputStreamExtensions","d":"better.files.Implicits","k":"def"},
{"l":"better/files/Implicits.html#OutputStreamExtensions-74d","e":false,"i":"","n":"OutputStreamExtensions","t":"OutputStreamExtensions(out: OutputStream): OutputStreamExtensions","d":"better.files.Implicits","k":"def"},
{"l":"better/files/Implicits.html#PathMatcherExtensions-c6d","e":false,"i":"","n":"PathMatcherExtensions","t":"PathMatcherExtensions(matcher: PathMatcher): PathMatcherExtensions","d":"better.files.Implicits","k":"def"},
{"l":"better/files/Implicits.html#PrintWriterExtensions-5a3","e":false,"i":"","n":"PrintWriterExtensions","t":"PrintWriterExtensions(pw: PrintWriter): PrintWriterExtensions","d":"better.files.Implicits","k":"def"},
{"l":"better/files/Implicits.html#ReaderExtensions-f8d","e":false,"i":"","n":"ReaderExtensions","t":"ReaderExtensions(reader: Reader): ReaderExtensions","d":"better.files.Implicits","k":"def"},
{"l":"better/files/Implicits.html#StringExtensions-e15","e":false,"i":"","n":"StringExtensions","t":"StringExtensions(str: String): StringExtensions","d":"better.files.Implicits","k":"def"},
{"l":"better/files/Implicits.html#StringInterpolations-cff","e":false,"i":"","n":"StringInterpolations","t":"StringInterpolations(sc: StringContext): StringInterpolations","d":"better.files.Implicits","k":"def"},
{"l":"better/files/Implicits.html#SymbolExtensions-581","e":false,"i":"","n":"SymbolExtensions","t":"SymbolExtensions(symbol: Symbol): SymbolExtensions","d":"better.files.Implicits","k":"def"},
{"l":"better/files/Implicits.html#URIExtensions-fda","e":false,"i":"","n":"URIExtensions","t":"URIExtensions(uri: URI): URIExtensions","d":"better.files.Implicits","k":"def"},
{"l":"better/files/Implicits.html#URLExtensions-2a0","e":false,"i":"","n":"URLExtensions","t":"URLExtensions(url: URL): URLExtensions","d":"better.files.Implicits","k":"def"},
{"l":"better/files/Implicits.html#WriterExtensions-fffffd8d","e":false,"i":"","n":"WriterExtensions","t":"WriterExtensions(writer: Writer): WriterExtensions","d":"better.files.Implicits","k":"def"},
{"l":"better/files/Implicits.html#ZipEntryExtensions-e9c","e":false,"i":"","n":"ZipEntryExtensions","t":"ZipEntryExtensions(entry: ZipEntry): ZipEntryExtensions","d":"better.files.Implicits","k":"def"},
{"l":"better/files/Implicits.html#ZipInputStreamExtensions-fffff21c","e":false,"i":"","n":"ZipInputStreamExtensions","t":"ZipInputStreamExtensions(in: ZipInputStream): ZipInputStreamExtensions","d":"better.files.Implicits","k":"def"},
{"l":"better/files/Implicits.html#ZipOutputStreamExtensions-fffffef6","e":false,"i":"","n":"ZipOutputStreamExtensions","t":"ZipOutputStreamExtensions(out: ZipOutputStream): ZipOutputStreamExtensions","d":"better.files.Implicits","k":"def"},
{"l":"better/files/Implicits.html#stringToCharset-fffff049","e":false,"i":"","n":"stringToCharset","t":"stringToCharset(charsetName: String): Charset","d":"better.files.Implicits","k":"def"},
{"l":"better/files/Implicits.html#stringToMessageDigest-fffff624","e":false,"i":"","n":"stringToMessageDigest","t":"stringToMessageDigest(algorithmName: String): MessageDigest","d":"better.files.Implicits","k":"def"},
{"l":"better/files/Implicits.html#tokenizerToIterator-fffff3b0","e":false,"i":"","n":"tokenizerToIterator","t":"tokenizerToIterator(s: StringTokenizer): Iterator[String]","d":"better.files.Implicits","k":"def"},
{"l":"better/files/Implicits$BufferedReaderExtensions.html#","e":false,"i":"","n":"BufferedReaderExtensions","t":"BufferedReaderExtensions(reader: BufferedReader)","d":"better.files.Implicits","k":"class"},
{"l":"better/files/Implicits$BufferedReaderExtensions.html#tokens-fffff229","e":false,"i":"","n":"tokens","t":"tokens(splitter: StringSplitter): Iterator[String]","d":"better.files.Implicits.BufferedReaderExtensions","k":"def"},
{"l":"better/files/Implicits$DigestInputStreamExtensions.html#","e":false,"i":"","n":"DigestInputStreamExtensions","t":"DigestInputStreamExtensions(in: DigestInputStream)","d":"better.files.Implicits","k":"class"},
{"l":"better/files/Implicits$DigestInputStreamExtensions.html#digest-fffff8af","e":false,"i":"","n":"digest","t":"digest(drainTo: OutputStream): Array[Byte]","d":"better.files.Implicits.DigestInputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$DigestInputStreamExtensions.html#hexDigest-62","e":false,"i":"","n":"hexDigest","t":"hexDigest(drainTo: OutputStream): String","d":"better.files.Implicits.DigestInputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$DisposeableExtensions.html#","e":false,"i":"","n":"DisposeableExtensions","t":"DisposeableExtensions[A](resource: A)(implicit evidence$1: Disposable[A])","d":"better.files.Implicits","k":"class"},
{"l":"better/files/Implicits$DisposeableExtensions.html#autoClosed-0","e":false,"i":"","n":"autoClosed","t":"autoClosed: Dispose[A]","d":"better.files.Implicits.DisposeableExtensions","k":"def"},
{"l":"better/files/Implicits$FileChannelExtensions.html#","e":false,"i":"","n":"FileChannelExtensions","t":"FileChannelExtensions(fc: FileChannel)","d":"better.files.Implicits","k":"class"},
{"l":"better/files/Implicits$FileChannelExtensions.html#toMappedByteBuffer-0","e":false,"i":"","n":"toMappedByteBuffer","t":"toMappedByteBuffer: MappedByteBuffer","d":"better.files.Implicits.FileChannelExtensions","k":"def"},
{"l":"better/files/Implicits$FileExtensions.html#","e":false,"i":"","n":"FileExtensions","t":"FileExtensions(file: File)","d":"better.files.Implicits","k":"class"},
{"l":"better/files/Implicits$FileExtensions.html#toScala-0","e":false,"i":"","n":"toScala","t":"toScala: File","d":"better.files.Implicits.FileExtensions","k":"def"},
{"l":"better/files/Implicits$InputStreamExtensions.html#","e":false,"i":"","n":"InputStreamExtensions","t":"InputStreamExtensions(in: InputStream)","d":"better.files.Implicits","k":"class"},
{"l":"better/files/Implicits$InputStreamExtensions.html#adler32-0","e":false,"i":"","n":"adler32","t":"adler32: CheckedInputStream","d":"better.files.Implicits.InputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$InputStreamExtensions.html#asGzipInputStream-dfc","e":false,"i":"","n":"asGzipInputStream","t":"asGzipInputStream(bufferSize: Int): GZIPInputStream","d":"better.files.Implicits.InputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$InputStreamExtensions.html#asObjectInputStream-348","e":false,"i":"","n":"asObjectInputStream","t":"asObjectInputStream(bufferSize: Int): ObjectInputStream","d":"better.files.Implicits.InputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$InputStreamExtensions.html#asObjectInputStreamUsingClassLoader-75f","e":false,"i":"","n":"asObjectInputStreamUsingClassLoader","t":"asObjectInputStreamUsingClassLoader(classLoader: ClassLoader, bufferSize: Int): ObjectInputStream","d":"better.files.Implicits.InputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$InputStreamExtensions.html#asString-810","e":false,"i":"","n":"asString","t":"asString(closeStream: Boolean, bufferSize: Int, charset: Charset): String","d":"better.files.Implicits.InputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$InputStreamExtensions.html#asZipInputStream-51a","e":false,"i":"","n":"asZipInputStream","t":"asZipInputStream(charset: Charset): ZipInputStream","d":"better.files.Implicits.InputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$InputStreamExtensions.html#buffered-0","e":false,"i":"","n":"buffered","t":"buffered: BufferedInputStream","d":"better.files.Implicits.InputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$InputStreamExtensions.html#buffered-e68","e":false,"i":"","n":"buffered","t":"buffered(bufferSize: Int): BufferedInputStream","d":"better.files.Implicits.InputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$InputStreamExtensions.html#byteArray-0","e":false,"i":"","n":"byteArray","t":"byteArray: Array[Byte]","d":"better.files.Implicits.InputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$InputStreamExtensions.html#bytes-0","e":false,"i":"","n":"bytes","t":"bytes: Iterator[Byte]","d":"better.files.Implicits.InputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$InputStreamExtensions.html#crc32-0","e":false,"i":"","n":"crc32","t":"crc32: CheckedInputStream","d":"better.files.Implicits.InputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$InputStreamExtensions.html#lines-d2","e":false,"i":"","n":"lines","t":"lines(charset: Charset): Iterator[String]","d":"better.files.Implicits.InputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$InputStreamExtensions.html#md5-0","e":false,"i":"","n":"md5","t":"md5: DigestInputStream","d":"better.files.Implicits.InputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$InputStreamExtensions.html#pipeTo-fffff2c7","e":false,"i":"","n":"pipeTo","t":"pipeTo(out: OutputStream, bufferSize: Int): OutputStream","d":"better.files.Implicits.InputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$InputStreamExtensions.html#pipeTo-f2c","e":false,"i":"","n":"pipeTo","t":"pipeTo(out: OutputStream, buffer: Array[Byte]): OutputStream","d":"better.files.Implicits.InputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$InputStreamExtensions.html#reader-e4d","e":false,"i":"","n":"reader","t":"reader(charset: Charset): InputStreamReader","d":"better.files.Implicits.InputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$InputStreamExtensions.html#sha1-0","e":false,"i":"","n":"sha1","t":"sha1: DigestInputStream","d":"better.files.Implicits.InputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$InputStreamExtensions.html#sha256-0","e":false,"i":"","n":"sha256","t":"sha256: DigestInputStream","d":"better.files.Implicits.InputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$InputStreamExtensions.html#sha512-0","e":false,"i":"","n":"sha512","t":"sha512: DigestInputStream","d":"better.files.Implicits.InputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$InputStreamExtensions.html#withChecksum-fffff9a0","e":false,"i":"","n":"withChecksum","t":"withChecksum(checksum: Checksum): CheckedInputStream","d":"better.files.Implicits.InputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$InputStreamExtensions.html#withMessageDigest-fffffebb","e":false,"i":"","n":"withMessageDigest","t":"withMessageDigest(digest: MessageDigest): DigestInputStream","d":"better.files.Implicits.InputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$IteratorExtensions.html#","e":false,"i":"","n":"IteratorExtensions","t":"IteratorExtensions[A](it: Iterator[A])","d":"better.files.Implicits","k":"class"},
{"l":"better/files/Implicits$IteratorExtensions.html#nonClosing-5d6","e":false,"i":"","n":"nonClosing","t":"nonClosing(closeInTheEnd: Boolean): Iterator[A]","d":"better.files.Implicits.IteratorExtensions","k":"def"},
{"l":"better/files/Implicits$IteratorExtensions.html#withHasNext-fffffea6","e":false,"i":"","n":"withHasNext","t":"withHasNext(f: => Boolean): Iterator[A]","d":"better.files.Implicits.IteratorExtensions","k":"def"},
{"l":"better/files/Implicits$JStreamExtensions.html#","e":false,"i":"","n":"JStreamExtensions","t":"JStreamExtensions[A](stream: Stream[A])","d":"better.files.Implicits","k":"class"},
{"l":"better/files/Implicits$JStreamExtensions.html#toAutoClosedIterator-0","e":false,"i":"","n":"toAutoClosedIterator","t":"toAutoClosedIterator: Iterator[A]","d":"better.files.Implicits.JStreamExtensions","k":"def"},
{"l":"better/files/Implicits$ObjectInputStreamExtensions.html#","e":false,"i":"","n":"ObjectInputStreamExtensions","t":"ObjectInputStreamExtensions(ois: ObjectInputStream)","d":"better.files.Implicits","k":"class"},
{"l":"better/files/Implicits$ObjectInputStreamExtensions.html#deserialize-fffff7c4","e":false,"i":"","n":"deserialize","t":"deserialize[A]: A","d":"better.files.Implicits.ObjectInputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$ObjectOutputStreamExtensions.html#","e":false,"i":"","n":"ObjectOutputStreamExtensions","t":"ObjectOutputStreamExtensions(val oos: ObjectOutputStream)","d":"better.files.Implicits","k":"class"},
{"l":"better/files/Implicits$ObjectOutputStreamExtensions.html#oos-0","e":false,"i":"","n":"oos","t":"oos: ObjectOutputStream","d":"better.files.Implicits.ObjectOutputStreamExtensions","k":"val"},
{"l":"better/files/Implicits$ObjectOutputStreamExtensions.html#serialize-137","e":false,"i":"","n":"serialize","t":"serialize(obj: Serializable): ObjectOutputStream","d":"better.files.Implicits.ObjectOutputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$OutputStreamExtensions.html#","e":false,"i":"","n":"OutputStreamExtensions","t":"OutputStreamExtensions(val out: OutputStream)","d":"better.files.Implicits","k":"class"},
{"l":"better/files/Implicits$OutputStreamExtensions.html#adler32-0","e":false,"i":"","n":"adler32","t":"adler32: CheckedOutputStream","d":"better.files.Implicits.OutputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$OutputStreamExtensions.html#asGzipOutputStream-fffff501","e":false,"i":"","n":"asGzipOutputStream","t":"asGzipOutputStream(bufferSize: Int, syncFlush: Boolean): GZIPOutputStream","d":"better.files.Implicits.OutputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$OutputStreamExtensions.html#asObjectOutputStream-fffffc43","e":false,"i":"","n":"asObjectOutputStream","t":"asObjectOutputStream(bufferSize: Int): ObjectOutputStream","d":"better.files.Implicits.OutputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$OutputStreamExtensions.html#asZipOutputStream-4b1","e":false,"i":"","n":"asZipOutputStream","t":"asZipOutputStream(charset: Charset): ZipOutputStream","d":"better.files.Implicits.OutputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$OutputStreamExtensions.html#buffered-0","e":false,"i":"","n":"buffered","t":"buffered: BufferedOutputStream","d":"better.files.Implicits.OutputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$OutputStreamExtensions.html#buffered-fffff523","e":false,"i":"","n":"buffered","t":"buffered(bufferSize: Int): BufferedOutputStream","d":"better.files.Implicits.OutputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$OutputStreamExtensions.html#crc32-0","e":false,"i":"","n":"crc32","t":"crc32: CheckedOutputStream","d":"better.files.Implicits.OutputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$OutputStreamExtensions.html#md5-0","e":false,"i":"","n":"md5","t":"md5: DigestOutputStream","d":"better.files.Implicits.OutputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$OutputStreamExtensions.html#out-0","e":false,"i":"","n":"out","t":"out: OutputStream","d":"better.files.Implicits.OutputStreamExtensions","k":"val"},
{"l":"better/files/Implicits$OutputStreamExtensions.html#printWriter-284","e":false,"i":"","n":"printWriter","t":"printWriter(autoFlush: Boolean): PrintWriter","d":"better.files.Implicits.OutputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$OutputStreamExtensions.html#sha1-0","e":false,"i":"","n":"sha1","t":"sha1: DigestOutputStream","d":"better.files.Implicits.OutputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$OutputStreamExtensions.html#sha256-0","e":false,"i":"","n":"sha256","t":"sha256: DigestOutputStream","d":"better.files.Implicits.OutputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$OutputStreamExtensions.html#sha512-0","e":false,"i":"","n":"sha512","t":"sha512: DigestOutputStream","d":"better.files.Implicits.OutputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$OutputStreamExtensions.html#tee-77a","e":false,"i":"","n":"tee","t":"tee(out2: OutputStream): OutputStream","d":"better.files.Implicits.OutputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$OutputStreamExtensions.html#withChecksum-eb","e":false,"i":"","n":"withChecksum","t":"withChecksum(checksum: Checksum): CheckedOutputStream","d":"better.files.Implicits.OutputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$OutputStreamExtensions.html#withMessageDigest-ffffff30","e":false,"i":"","n":"withMessageDigest","t":"withMessageDigest(digest: MessageDigest): DigestOutputStream","d":"better.files.Implicits.OutputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$OutputStreamExtensions.html#write-fffffc2e","e":false,"i":"","n":"write","t":"write(bytes: Iterator[Byte], bufferSize: Int): OutputStream","d":"better.files.Implicits.OutputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$OutputStreamExtensions.html#writeAndClose-255","e":false,"i":"","n":"writeAndClose","t":"writeAndClose(str: String, charset: Charset): Unit","d":"better.files.Implicits.OutputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$OutputStreamExtensions.html#writer-6b4","e":false,"i":"","n":"writer","t":"writer(charset: Charset): OutputStreamWriter","d":"better.files.Implicits.OutputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$PathMatcherExtensions.html#","e":false,"i":"","n":"PathMatcherExtensions","t":"PathMatcherExtensions(matcher: PathMatcher)","d":"better.files.Implicits","k":"class"},
{"l":"better/files/Implicits$PathMatcherExtensions.html#matches-bd5","e":false,"i":"","n":"matches","t":"matches(file: File, maxDepth: Int, visitOptions: VisitOptions): Iterator[File]","d":"better.files.Implicits.PathMatcherExtensions","k":"def"},
{"l":"better/files/Implicits$PrintWriterExtensions.html#","e":false,"i":"","n":"PrintWriterExtensions","t":"PrintWriterExtensions(pw: PrintWriter)","d":"better.files.Implicits","k":"class"},
{"l":"better/files/Implicits$PrintWriterExtensions.html#printLines-fffff729","e":false,"i":"","n":"printLines","t":"printLines(lines: IterableOnce[_]): PrintWriter","d":"better.files.Implicits.PrintWriterExtensions","k":"def"},
{"l":"better/files/Implicits$ReaderExtensions.html#","e":false,"i":"","n":"ReaderExtensions","t":"ReaderExtensions(reader: Reader)","d":"better.files.Implicits","k":"class"},
{"l":"better/files/Implicits$ReaderExtensions.html#buffered-0","e":false,"i":"","n":"buffered","t":"buffered: BufferedReader","d":"better.files.Implicits.ReaderExtensions","k":"def"},
{"l":"better/files/Implicits$ReaderExtensions.html#chars-0","e":false,"i":"","n":"chars","t":"chars: Iterator[Char]","d":"better.files.Implicits.ReaderExtensions","k":"def"},
{"l":"better/files/Implicits$ReaderExtensions.html#toInputStream-f63","e":false,"i":"","n":"toInputStream","t":"toInputStream(bufferSize: Int, charset: Charset): InputStream","d":"better.files.Implicits.ReaderExtensions","k":"def"},
{"l":"better/files/Implicits$StringExtensions.html#","e":false,"i":"","n":"StringExtensions","t":"StringExtensions(str: String)","d":"better.files.Implicits","k":"class"},
{"l":"better/files/Implicits$StringExtensions.html#/-fffff5ac","e":false,"i":"","n":"/","t":"/(child: String): File","d":"better.files.Implicits.StringExtensions","k":"def"},
{"l":"better/files/Implicits$StringExtensions.html#inputStream-ea","e":false,"i":"","n":"inputStream","t":"inputStream(charset: Charset): InputStream","d":"better.files.Implicits.StringExtensions","k":"def"},
{"l":"better/files/Implicits$StringExtensions.html#reader-0","e":false,"i":"","n":"reader","t":"reader: Reader","d":"better.files.Implicits.StringExtensions","k":"def"},
{"l":"better/files/Implicits$StringExtensions.html#toFile-0","e":false,"i":"","n":"toFile","t":"toFile: File","d":"better.files.Implicits.StringExtensions","k":"def"},
{"l":"better/files/Implicits$StringInterpolations.html#","e":false,"i":"","n":"StringInterpolations","t":"StringInterpolations(sc: StringContext)","d":"better.files.Implicits","k":"class"},
{"l":"better/files/Implicits$StringInterpolations.html#file-6a6","e":false,"i":"","n":"file","t":"file(args: Any*): File","d":"better.files.Implicits.StringInterpolations","k":"def"},
{"l":"better/files/Implicits$SymbolExtensions.html#","e":false,"i":"","n":"SymbolExtensions","t":"SymbolExtensions(symbol: Symbol)","d":"better.files.Implicits","k":"class"},
{"l":"better/files/Implicits$SymbolExtensions.html#/-e11","e":false,"i":"","n":"/","t":"/(child: Symbol): File","d":"better.files.Implicits.SymbolExtensions","k":"def"},
{"l":"better/files/Implicits$URIExtensions.html#","e":false,"i":"","n":"URIExtensions","t":"URIExtensions(uri: URI)","d":"better.files.Implicits","k":"class"},
{"l":"better/files/Implicits$URIExtensions.html#isFile-0","e":false,"i":"","n":"isFile","t":"isFile: Boolean","d":"better.files.Implicits.URIExtensions","k":"def"},
{"l":"better/files/Implicits$URIExtensions.html#toFile-0","e":false,"i":"","n":"toFile","t":"toFile: Option[File]","d":"better.files.Implicits.URIExtensions","k":"def"},
{"l":"better/files/Implicits$URIExtensions.html#toFileUnsafe-0","e":false,"i":"","n":"toFileUnsafe","t":"toFileUnsafe: File","d":"better.files.Implicits.URIExtensions","k":"def"},
{"l":"better/files/Implicits$URLExtensions.html#","e":false,"i":"","n":"URLExtensions","t":"URLExtensions(url: URL)","d":"better.files.Implicits","k":"class"},
{"l":"better/files/Implicits$URLExtensions.html#isFile-0","e":false,"i":"","n":"isFile","t":"isFile: Boolean","d":"better.files.Implicits.URLExtensions","k":"def"},
{"l":"better/files/Implicits$URLExtensions.html#toFile-0","e":false,"i":"","n":"toFile","t":"toFile: Option[File]","d":"better.files.Implicits.URLExtensions","k":"def"},
{"l":"better/files/Implicits$URLExtensions.html#toFileUnsafe-0","e":false,"i":"","n":"toFileUnsafe","t":"toFileUnsafe: File","d":"better.files.Implicits.URLExtensions","k":"def"},
{"l":"better/files/Implicits$WriterExtensions.html#","e":false,"i":"","n":"WriterExtensions","t":"WriterExtensions(writer: Writer)","d":"better.files.Implicits","k":"class"},
{"l":"better/files/Implicits$WriterExtensions.html#buffered-0","e":false,"i":"","n":"buffered","t":"buffered: BufferedWriter","d":"better.files.Implicits.WriterExtensions","k":"def"},
{"l":"better/files/Implicits$WriterExtensions.html#outputstream-fffff0fa","e":false,"i":"","n":"outputstream","t":"outputstream(bufferSize: Int, flushImmediately: Boolean, charset: Charset): OutputStream","d":"better.files.Implicits.WriterExtensions","k":"def"},
{"l":"better/files/Implicits$ZipEntryExtensions.html#","e":false,"i":"","n":"ZipEntryExtensions","t":"ZipEntryExtensions(val entry: ZipEntry)","d":"better.files.Implicits","k":"class"},
{"l":"better/files/Implicits$ZipEntryExtensions.html#entry-0","e":false,"i":"","n":"entry","t":"entry: ZipEntry","d":"better.files.Implicits.ZipEntryExtensions","k":"val"},
{"l":"better/files/Implicits$ZipEntryExtensions.html#extractTo-452","e":false,"i":"","n":"extractTo","t":"extractTo(rootDir: File, inputStream: => InputStream): File","d":"better.files.Implicits.ZipEntryExtensions","k":"def"},
{"l":"better/files/Implicits$ZipInputStreamExtensions.html#","e":false,"i":"","n":"ZipInputStreamExtensions","t":"ZipInputStreamExtensions(val in: ZipInputStream)","d":"better.files.Implicits","k":"class"},
{"l":"better/files/Implicits$ZipInputStreamExtensions.html#foldMap-fffffcf6","e":false,"i":"","n":"foldMap","t":"foldMap[A](f: ZipInputStream => A): Iterator[A]","d":"better.files.Implicits.ZipInputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$ZipInputStreamExtensions.html#in-0","e":false,"i":"","n":"in","t":"in: ZipInputStream","d":"better.files.Implicits.ZipInputStreamExtensions","k":"val"},
{"l":"better/files/Implicits$ZipInputStreamExtensions.html#mapEntries-fffffcf6","e":false,"i":"","n":"mapEntries","t":"mapEntries[A](f: ZipEntry => A): Iterator[A]","d":"better.files.Implicits.ZipInputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$ZipOutputStreamExtensions.html#","e":false,"i":"","n":"ZipOutputStreamExtensions","t":"ZipOutputStreamExtensions(val out: ZipOutputStream)","d":"better.files.Implicits","k":"class"},
{"l":"better/files/Implicits$ZipOutputStreamExtensions.html#+=-f44","e":false,"i":"","n":"+=","t":"+=(file: File): ZipOutputStream","d":"better.files.Implicits.ZipOutputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$ZipOutputStreamExtensions.html#add-fffff0ff","e":false,"i":"","n":"add","t":"add(file: File, name: String): ZipOutputStream","d":"better.files.Implicits.ZipOutputStreamExtensions","k":"def"},
{"l":"better/files/Implicits$ZipOutputStreamExtensions.html#out-0","e":false,"i":"","n":"out","t":"out: ZipOutputStream","d":"better.files.Implicits.ZipOutputStreamExtensions","k":"val"},
{"l":"better/files/Implicits$ZipOutputStreamExtensions.html#withCompressionLevel-fffff94e","e":false,"i":"","n":"withCompressionLevel","t":"withCompressionLevel(level: Int): ZipOutputStream","d":"better.files.Implicits.ZipOutputStreamExtensions","k":"def"},
{"l":"better/files/NullOutputStream$.html#","e":false,"i":"","n":"NullOutputStream","t":"NullOutputStream extends OutputStream","d":"better.files","k":"object"},
{"l":"better/files/ReaderInputStream.html#","e":false,"i":"","n":"ReaderInputStream","t":"ReaderInputStream(reader: Reader, encoder: CharsetEncoder, bufferSize: Int) extends InputStream","d":"better.files","k":"class"},
{"l":"better/files/ReaderInputStream.html#<init>-fffffd5e","e":false,"i":"","n":"this","t":"this(reader: Reader, bufferSize: Int, charset: Charset)","d":"better.files.ReaderInputStream","k":"def"},
{"l":"better/files/Resource.html#","e":false,"i":"","n":"Resource","t":"Resource","d":"better.files","k":"trait"},
{"l":"better/files/Resource.html#asStream-fffffd22","e":false,"i":"","n":"asStream","t":"asStream(name: String): Option[InputStream]","d":"better.files.Resource","k":"def"},
{"l":"better/files/Resource.html#asString-a83","e":false,"i":"","n":"asString","t":"asString(name: String, bufferSize: Int, charset: Charset): Option[String]","d":"better.files.Resource","k":"def"},
{"l":"better/files/Resource.html#getAsStream-fffff9c9","e":false,"i":"","n":"getAsStream","t":"getAsStream(name: String): InputStream","d":"better.files.Resource","k":"def"},
{"l":"better/files/Resource.html#getAsString-7ab","e":false,"i":"","n":"getAsString","t":"getAsString(name: String, bufferSize: Int, charset: Charset): String","d":"better.files.Resource","k":"def"},
{"l":"better/files/Resource.html#getUrl-fffff497","e":false,"i":"","n":"getUrl","t":"getUrl(name: String): URL","d":"better.files.Resource","k":"def"},
{"l":"better/files/Resource.html#url-fffffd22","e":false,"i":"","n":"url","t":"url(name: String): Option[URL]","d":"better.files.Resource","k":"def"},
{"l":"better/files/Resource$.html#","e":false,"i":"","n":"Resource","t":"Resource extends Resource","d":"better.files","k":"object"},
{"l":"better/files/Resource$.html#at-fffff75f","e":false,"i":"","n":"at","t":"at(clazz: Class[_]): Resource","d":"better.files.Resource","k":"def"},
{"l":"better/files/Resource$.html#at-fffff9f2","e":false,"i":"","n":"at","t":"at[T]: Resource","d":"better.files.Resource","k":"def"},
{"l":"better/files/Resource$.html#from-fffff40c","e":false,"i":"","n":"from","t":"from(cl: ClassLoader): Resource","d":"better.files.Resource","k":"def"},
{"l":"better/files/Resource$.html#my-0","e":false,"i":"","n":"my","t":"my: Resource","d":"better.files.Resource","k":"def"},
{"l":"better/files/Resource$.html#notFound-8c0","e":false,"i":"","n":"notFound","t":"notFound(name: String): Nothing","d":"better.files.Resource","k":"def"},
{"l":"better/files/Scannable.html#","e":false,"i":"","n":"Scannable","t":"Scannable[A]","d":"better.files","k":"trait"},
{"l":"better/files/Scannable.html#apply-d7c","e":false,"i":"","n":"apply","t":"apply(scanner: Scanner): A","d":"better.files.Scannable","k":"def"},
{"l":"better/files/Scannable$.html#","e":false,"i":"","n":"Scannable","t":"Scannable","d":"better.files","k":"object"},
{"l":"better/files/Scannable$.html#apply-bd6","e":false,"i":"","n":"apply","t":"apply[A](f: Scanner => A): Scannable[A]","d":"better.files.Scannable","k":"def"},
{"l":"better/files/Scannable$.html#fromRead-570","e":false,"i":"","n":"fromRead","t":"fromRead[A](implicit read: Read[A]): Scannable[A]","d":"better.files.Scannable","k":"def"},
{"l":"better/files/Scannable$.html#iterator-55d","e":false,"i":"","n":"iterator","t":"iterator[A](implicit scanner: Scannable[A]): Scannable[Iterator[A]]","d":"better.files.Scannable","k":"def"},
{"l":"better/files/Scannable$.html#tuple2-cf4","e":false,"i":"","n":"tuple2","t":"tuple2[T1, T2](implicit t1: Scannable[T1], t2: Scannable[T2]): Scannable[(T1, T2)]","d":"better.files.Scannable","k":"def"},
{"l":"better/files/StringSplitter.html#","e":false,"i":"","n":"StringSplitter","t":"StringSplitter","d":"better.files","k":"trait"},
{"l":"better/files/StringSplitter.html#split-296","e":false,"i":"","n":"split","t":"split(s: String): IterableOnce[String]","d":"better.files.StringSplitter","k":"def"},
{"l":"better/files/StringSplitter$.html#","e":false,"i":"","n":"StringSplitter","t":"StringSplitter","d":"better.files","k":"object"},
{"l":"better/files/StringSplitter$.html#Default-0","e":false,"i":"","n":"Default","t":"Default: StringSplitter","d":"better.files.StringSplitter","k":"val"},
{"l":"better/files/StringSplitter$.html#anyOf-5b2","e":false,"i":"","n":"anyOf","t":"anyOf(delimiters: String, includeDelimiters: Boolean): StringSplitter","d":"better.files.StringSplitter","k":"def"},
{"l":"better/files/StringSplitter$.html#on-5cf","e":false,"i":"","n":"on","t":"on(delimiter: Char): StringSplitter","d":"better.files.StringSplitter","k":"def"},
{"l":"better/files/StringSplitter$.html#regex-e28","e":false,"i":"","n":"regex","t":"regex(pattern: String): StringSplitter","d":"better.files.StringSplitter","k":"def"},
{"l":"better/files/TeeOutputStream.html#","e":false,"i":"","n":"TeeOutputStream","t":"TeeOutputStream(outs: OutputStream*) extends OutputStream","d":"better.files","k":"class"},
{"l":"better/files/UnicodeCharset.html#","e":false,"i":"","n":"UnicodeCharset","t":"UnicodeCharset(underlyingCharset: Charset, writeByteOrderMarkers: Boolean) extends Charset","d":"better.files","k":"class"},
{"l":"better/files/UnicodeCharset$.html#","e":false,"i":"","n":"UnicodeCharset","t":"UnicodeCharset","d":"better.files","k":"object"},
{"l":"better/files/UnicodeCharset$.html#apply-fffff5e0","e":false,"i":"","n":"apply","t":"apply(charset: Charset, writeByteOrderMarkers: Boolean): Charset","d":"better.files.UnicodeCharset","k":"def"},
{"l":"better/files/UnicodeCharset$.html#isValid-fc","e":false,"i":"","n":"isValid","t":"isValid(charset: Charset): Boolean","d":"better.files.UnicodeCharset","k":"def"},
{"l":"better/files/UnicodeDecoder.html#","e":false,"i":"","n":"UnicodeDecoder","t":"UnicodeDecoder(defaultCharset: Charset) extends CharsetDecoder","d":"better.files","k":"class"},
{"l":"better/files/WriterOutputStream.html#","e":false,"i":"","n":"WriterOutputStream","t":"WriterOutputStream(writer: Writer, decoder: CharsetDecoder, bufferSize: Int, flushImmediately: Boolean) extends OutputStream","d":"better.files","k":"class"},
{"l":"better/files/WriterOutputStream.html#<init>-dd","e":false,"i":"","n":"this","t":"this(writer: Writer, bufferSize: Int, flushImmediately: Boolean, charset: Charset)","d":"better.files.WriterOutputStream","k":"def"}];