addSbtPlugin("com.github.sbt"            % "sbt-ci-release"   % "1.5.11")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"    % "2.0.7")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"      % "0.4.2")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"     % "0.4.2")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"     % "2.5.0")
addSbtPlugin("com.github.sbt"            % "sbt-site-paradox" % "1.5.0-RC2")
