addSbtPlugin("com.geirsson"              % "sbt-ci-release"      % "1.5.7")
addSbtPlugin("com.eed3si9n"              % "sbt-unidoc"          % "0.4.3")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"       % "1.6.1")
addSbtPlugin("com.timushev.sbt"          % "sbt-updates"         % "0.4.2")
addSbtPlugin("com.github.sbt"            % "sbt-ghpages"         % "0.7.0")
addSbtPlugin("com.codacy"                % "sbt-codacy-coverage" % "3.0.3")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"        % "0.1.17")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.0.4")
